export enum LazorKitDocsSection {
    OVERVIEW = 'OVERVIEW',
    INSTALLATION = 'INSTALLATION',
    CONFIGURATION = 'CONFIGURATION',
    PASSKEY_WALLET = 'PASSKEY_WALLET',
    GASLESS_TRANSACTIONS = 'GASLESS_TRANSACTIONS',
    SESSION_PERSISTENCE = 'SESSION_PERSISTENCE',
    API_REFERENCE = 'API_REFERENCE',
    ERROR_HANDLING = 'ERROR_HANDLING',
    BEST_PRACTICES = 'BEST_PRACTICES',
    TROUBLESHOOTING = 'TROUBLESHOOTING',
}
